version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flaskuser"]
      interval: 5s
      timeout: 5s
      retries: 5


  web:
    build: .
    container_name: flask-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://flaskuser:flaskpass@db:5432/flaskdb
    ports:
      - "5000:5000"
    networks:
      - flask-net

volumes:
  postgres_data:

networks:
  flask-net: